-- --------------------------------------------------------
-- Διακομιστής:                  127.0.0.1
-- Έκδοση διακομιστή:            10.4.28-MariaDB - mariadb.org binary distribution
-- Λειτ. σύστημα διακομιστή:     Win64
-- HeidiSQL Έκδοση:              12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping database structure for adise23_griniaris
CREATE DATABASE IF NOT EXISTS `adise23_griniaris` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `adise23_griniaris`;

-- Dumping structure for πίνακας adise23_griniaris.board
CREATE TABLE IF NOT EXISTS `board` (
  `x` tinyint(1) NOT NULL,
  `y` tinyint(1) NOT NULL,
  `b_color` enum('R','G','B','Y','W','MIX','GR','RY','BY','GB') NOT NULL,
  `piece_color` enum('R','G','B','Y') DEFAULT NULL,
  `piece` enum('R1','R2','R3','R4','G1','G2','G3','G4','B1','B2','B3','B4','Y1','Y2','Y3','Y4') DEFAULT NULL,
  `y_path` int(11) DEFAULT NULL CHECK (`y_path` is null or `y_path` >= 1 and `y_path` <= 55),
  `b_path` int(11) DEFAULT NULL CHECK (`b_path` is null or `b_path` >= 1 and `b_path` <= 55),
  `r_path` int(11) DEFAULT NULL CHECK (`r_path` is null or `r_path` >= 1 and `r_path` <= 55),
  `g_path` int(11) DEFAULT NULL CHECK (`g_path` is null or `g_path` >= 1 and `g_path` <= 55),
  PRIMARY KEY (`x`,`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table adise23_griniaris.board: ~225 rows (approximately)
INSERT INTO `board` (`x`, `y`, `b_color`, `piece_color`, `piece`, `y_path`, `b_path`, `r_path`, `g_path`) VALUES
	(1, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 3, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 5, 'W', NULL, NULL, 33, 20, 46, 7),
	(1, 6, 'W', NULL, NULL, 34, 21, 47, 8),
	(1, 7, 'W', NULL, NULL, 35, 22, 48, 9),
	(1, 8, 'W', NULL, NULL, 36, 23, 49, 10),
	(1, 9, 'W', NULL, NULL, 37, 24, NULL, 11),
	(1, 10, 'W', NULL, NULL, 38, 25, NULL, 12),
	(1, 11, 'W', NULL, NULL, 39, 26, NULL, 13),
	(1, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 13, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 14, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 2, 'W', 'G', 'G3', NULL, NULL, NULL, NULL),
	(2, 3, 'W', 'G', 'G1', NULL, NULL, NULL, NULL),
	(2, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 5, 'W', NULL, NULL, 32, 19, 45, 6),
	(2, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 8, 'R', NULL, NULL, NULL, NULL, 50, NULL),
	(2, 9, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 10, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 11, 'R', NULL, NULL, 40, 27, 1, 14),
	(2, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 13, 'W', 'R', 'R3', NULL, NULL, NULL, NULL),
	(2, 14, 'W', 'R', 'R1', NULL, NULL, NULL, NULL),
	(2, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 2, 'W', 'G', 'G4', NULL, NULL, NULL, NULL),
	(3, 3, 'W', 'G', 'G2', NULL, NULL, NULL, NULL),
	(3, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 5, 'W', NULL, NULL, 31, 18, 44, 5),
	(3, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 8, 'R', NULL, NULL, NULL, NULL, 51, NULL),
	(3, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 11, 'W', NULL, NULL, 41, 28, 2, 15),
	(3, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 13, 'W', 'R', 'R4', NULL, NULL, NULL, NULL),
	(3, 14, 'W', 'R', 'R2', NULL, NULL, NULL, NULL),
	(3, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 3, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 5, 'W', NULL, NULL, 30, 17, 43, 4),
	(4, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 8, 'R', NULL, NULL, NULL, NULL, 52, NULL),
	(4, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 11, 'W', NULL, NULL, 42, 29, 3, 16),
	(4, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 13, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 14, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 1, 'W', NULL, NULL, 26, 13, 39, NULL),
	(5, 2, 'G', NULL, NULL, 27, 14, 40, 1),
	(5, 3, 'W', NULL, NULL, 28, 15, 41, 2),
	(5, 4, 'W', NULL, NULL, 29, 16, 42, 3),
	(5, 5, 'GR', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 6, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 7, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 8, 'R', NULL, NULL, NULL, NULL, 53, NULL),
	(5, 9, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 10, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 12, 'W', NULL, NULL, 43, 30, 4, 17),
	(5, 13, 'W', NULL, NULL, 44, 31, 5, 18),
	(5, 14, 'W', NULL, NULL, 45, 32, 6, 19),
	(5, 15, 'W', NULL, NULL, 46, 33, 7, 20),
	(6, 1, 'W', NULL, NULL, 25, 12, 38, NULL),
	(6, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 6, 'GR', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 7, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 8, 'R', NULL, NULL, NULL, NULL, 54, NULL),
	(6, 9, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 10, 'RY', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 14, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 15, 'W', NULL, NULL, 47, 34, 8, 21),
	(7, 1, 'W', NULL, NULL, 24, 11, 37, NULL),
	(7, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 6, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 7, 'GR', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 8, 'R', NULL, NULL, NULL, NULL, 55, NULL),
	(7, 9, 'RY', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 10, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 14, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 15, 'W', NULL, NULL, 48, 35, 9, 22),
	(8, 1, 'W', NULL, NULL, 23, 10, 36, 49),
	(8, 2, 'G', NULL, NULL, NULL, NULL, NULL, 50),
	(8, 3, 'G', NULL, NULL, NULL, NULL, NULL, 51),
	(8, 4, 'G', NULL, NULL, NULL, NULL, NULL, 52),
	(8, 5, 'G', NULL, NULL, NULL, NULL, NULL, 53),
	(8, 6, 'G', NULL, NULL, NULL, NULL, NULL, 54),
	(8, 7, 'G', NULL, NULL, NULL, NULL, NULL, 55),
	(8, 8, 'MIX', NULL, NULL, NULL, NULL, NULL, NULL),
	(8, 9, 'Y', NULL, NULL, 55, NULL, NULL, NULL),
	(8, 10, 'Y', NULL, NULL, 54, NULL, NULL, NULL),
	(8, 11, 'Y', NULL, NULL, 53, NULL, NULL, NULL),
	(8, 12, 'Y', NULL, NULL, 52, NULL, NULL, NULL),
	(8, 13, 'Y', NULL, NULL, 51, NULL, NULL, NULL),
	(8, 14, 'Y', NULL, NULL, 50, NULL, NULL, NULL),
	(8, 15, 'W', NULL, NULL, 49, 36, 10, 23),
	(9, 1, 'W', NULL, NULL, 22, 9, 35, 48),
	(9, 2, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 6, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 7, 'GB', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 8, 'B', NULL, NULL, NULL, 55, NULL, NULL),
	(9, 9, 'BY', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 10, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 15, 'W', NULL, NULL, NULL, 37, 11, 24),
	(10, 1, 'W', NULL, NULL, 21, 8, 34, 47),
	(10, 2, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 6, 'GB', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 7, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 8, 'B', NULL, NULL, NULL, 54, NULL, NULL),
	(10, 9, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 10, 'BY', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 11, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 15, 'W', NULL, NULL, NULL, 38, 12, 25),
	(11, 1, 'W', NULL, NULL, 20, 7, 33, 46),
	(11, 2, 'W', NULL, NULL, 19, 6, 32, 45),
	(11, 3, 'W', NULL, NULL, 18, 5, 31, 44),
	(11, 4, 'W', NULL, NULL, 17, 4, 30, 43),
	(11, 5, 'GB', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 6, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 7, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 8, 'B', NULL, NULL, NULL, 53, NULL, NULL),
	(11, 9, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 10, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 11, 'BY', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 12, 'W', NULL, NULL, 3, 42, 16, 29),
	(11, 13, 'W', NULL, NULL, 2, 41, 15, 28),
	(11, 14, 'Y', NULL, NULL, 1, 40, 14, 27),
	(11, 15, 'W', NULL, NULL, NULL, 39, 13, 26),
	(12, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 2, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 3, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 5, 'W', NULL, NULL, 16, 3, 29, 42),
	(12, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 8, 'B', NULL, NULL, NULL, 52, NULL, NULL),
	(12, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 11, 'W', NULL, NULL, 4, 43, 17, 30),
	(12, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 13, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 2, 'W', 'B', 'B3', NULL, NULL, NULL, NULL),
	(13, 3, 'W', 'B', 'B1', NULL, NULL, NULL, NULL),
	(13, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 5, 'W', NULL, NULL, 15, 2, 28, 41),
	(13, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 8, 'B', NULL, NULL, NULL, 51, NULL, NULL),
	(13, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 11, 'W', NULL, NULL, 5, 44, 18, 31),
	(13, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 13, 'W', 'Y', 'Y3', NULL, NULL, NULL, NULL),
	(13, 14, 'W', 'Y', 'Y1', NULL, NULL, NULL, NULL),
	(13, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 2, 'W', 'B', 'B4', NULL, NULL, NULL, NULL),
	(14, 3, 'W', 'B', 'B2', NULL, NULL, NULL, NULL),
	(14, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 5, 'B', NULL, NULL, 14, 1, 27, 40),
	(14, 6, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 7, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 8, 'B', NULL, NULL, NULL, 50, NULL, NULL),
	(14, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 11, 'W', NULL, NULL, 6, 45, 19, 32),
	(14, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 13, 'W', 'Y', 'Y4', NULL, NULL, NULL, NULL),
	(14, 14, 'W', 'Y', 'Y2', NULL, NULL, NULL, NULL),
	(14, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 2, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 3, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 5, 'W', NULL, NULL, 13, NULL, 26, 39),
	(15, 6, 'W', NULL, NULL, 12, NULL, 25, 38),
	(15, 7, 'W', NULL, NULL, 11, NULL, 24, 37),
	(15, 8, 'W', NULL, NULL, 10, 49, 23, 36),
	(15, 9, 'W', NULL, NULL, 9, 48, 22, 35),
	(15, 10, 'W', NULL, NULL, 8, 47, 21, 34),
	(15, 11, 'W', NULL, NULL, 7, 46, 20, 33),
	(15, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 13, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL);

-- Dumping structure for πίνακας adise23_griniaris.board_empty
CREATE TABLE IF NOT EXISTS `board_empty` (
  `x` tinyint(1) NOT NULL,
  `y` tinyint(1) NOT NULL,
  `b_color` enum('R','G','B','Y','W','MIX','GR','RY','BY','GB') NOT NULL,
  `piece_color` enum('R','G','B','Y') DEFAULT NULL,
  `piece` enum('R1','R2','R3','R4','G1','G2','G3','G4','B1','B2','B3','B4','Y1','Y2','Y3','Y4') DEFAULT NULL,
  `y_path` int(11) DEFAULT NULL CHECK (`y_path` is null or `y_path` >= 1 and `y_path` <= 55),
  `b_path` int(11) DEFAULT NULL CHECK (`b_path` is null or `b_path` >= 1 and `b_path` <= 55),
  `r_path` int(11) DEFAULT NULL CHECK (`r_path` is null or `r_path` >= 1 and `r_path` <= 55),
  `g_path` int(11) DEFAULT NULL CHECK (`g_path` is null or `g_path` >= 1 and `g_path` <= 55),
  PRIMARY KEY (`x`,`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table adise23_griniaris.board_empty: ~225 rows (approximately)
INSERT INTO `board_empty` (`x`, `y`, `b_color`, `piece_color`, `piece`, `y_path`, `b_path`, `r_path`, `g_path`) VALUES
	(1, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 3, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 5, 'W', NULL, NULL, 33, 20, 46, 7),
	(1, 6, 'W', NULL, NULL, 34, 21, 47, 8),
	(1, 7, 'W', NULL, NULL, 35, 22, 48, 9),
	(1, 8, 'W', NULL, NULL, 36, 23, 49, 10),
	(1, 9, 'W', NULL, NULL, 37, 24, NULL, 11),
	(1, 10, 'W', NULL, NULL, 38, 25, NULL, 12),
	(1, 11, 'W', NULL, NULL, 39, 26, NULL, 13),
	(1, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 13, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 14, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(1, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 2, 'W', 'G', 'G3', NULL, NULL, NULL, NULL),
	(2, 3, 'W', 'G', 'G1', NULL, NULL, NULL, NULL),
	(2, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 5, 'W', NULL, NULL, 32, 19, 45, 6),
	(2, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 8, 'R', NULL, NULL, NULL, NULL, 50, NULL),
	(2, 9, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 10, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 11, 'R', NULL, NULL, 40, 27, 1, 14),
	(2, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 13, 'W', 'R', 'R3', NULL, NULL, NULL, NULL),
	(2, 14, 'W', 'R', 'R1', NULL, NULL, NULL, NULL),
	(2, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 2, 'W', 'G', 'G4', NULL, NULL, NULL, NULL),
	(3, 3, 'W', 'G', 'G2', NULL, NULL, NULL, NULL),
	(3, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 5, 'W', NULL, NULL, 31, 18, 44, 5),
	(3, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 8, 'R', NULL, NULL, NULL, NULL, 51, NULL),
	(3, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 11, 'W', NULL, NULL, 41, 28, 2, 15),
	(3, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 13, 'W', 'R', 'R4', NULL, NULL, NULL, NULL),
	(3, 14, 'W', 'R', 'R2', NULL, NULL, NULL, NULL),
	(3, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 1, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 3, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 4, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 5, 'W', NULL, NULL, 30, 17, 43, 4),
	(4, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 8, 'R', NULL, NULL, NULL, NULL, 52, NULL),
	(4, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 11, 'W', NULL, NULL, 42, 29, 3, 16),
	(4, 12, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 13, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 14, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 15, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 1, 'W', NULL, NULL, 26, 13, 39, NULL),
	(5, 2, 'G', NULL, NULL, 27, 14, 40, 1),
	(5, 3, 'W', NULL, NULL, 28, 15, 41, 2),
	(5, 4, 'W', NULL, NULL, 29, 16, 42, 3),
	(5, 5, 'GR', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 6, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 7, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 8, 'R', NULL, NULL, NULL, NULL, 53, NULL),
	(5, 9, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 10, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 12, 'W', NULL, NULL, 43, 30, 4, 17),
	(5, 13, 'W', NULL, NULL, 44, 31, 5, 18),
	(5, 14, 'W', NULL, NULL, 45, 32, 6, 19),
	(5, 15, 'W', NULL, NULL, 46, 33, 7, 20),
	(6, 1, 'W', NULL, NULL, 25, 12, 38, NULL),
	(6, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 6, 'GR', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 7, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 8, 'R', NULL, NULL, NULL, NULL, 54, NULL),
	(6, 9, 'R', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 10, 'RY', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 14, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 15, 'W', NULL, NULL, 47, 34, 8, 21),
	(7, 1, 'W', NULL, NULL, 24, 11, 37, NULL),
	(7, 2, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 6, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 7, 'GR', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 8, 'R', NULL, NULL, NULL, NULL, 55, NULL),
	(7, 9, 'RY', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 10, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 14, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 15, 'W', NULL, NULL, 48, 35, 9, 22),
	(8, 1, 'W', NULL, NULL, 23, 10, 36, 49),
	(8, 2, 'G', NULL, NULL, NULL, NULL, NULL, 50),
	(8, 3, 'G', NULL, NULL, NULL, NULL, NULL, 51),
	(8, 4, 'G', NULL, NULL, NULL, NULL, NULL, 52),
	(8, 5, 'G', NULL, NULL, NULL, NULL, NULL, 53),
	(8, 6, 'G', NULL, NULL, NULL, NULL, NULL, 54),
	(8, 7, 'G', NULL, NULL, NULL, NULL, NULL, 55),
	(8, 8, 'MIX', NULL, NULL, NULL, NULL, NULL, NULL),
	(8, 9, 'Y', NULL, NULL, 55, NULL, NULL, NULL),
	(8, 10, 'Y', NULL, NULL, 54, NULL, NULL, NULL),
	(8, 11, 'Y', NULL, NULL, 53, NULL, NULL, NULL),
	(8, 12, 'Y', NULL, NULL, 52, NULL, NULL, NULL),
	(8, 13, 'Y', NULL, NULL, 51, NULL, NULL, NULL),
	(8, 14, 'Y', NULL, NULL, 50, NULL, NULL, NULL),
	(8, 15, 'W', NULL, NULL, 49, 36, 10, 23),
	(9, 1, 'W', NULL, NULL, 22, 9, 35, 48),
	(9, 2, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 6, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 7, 'GB', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 8, 'B', NULL, NULL, NULL, 55, NULL, NULL),
	(9, 9, 'BY', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 10, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 11, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 15, 'W', NULL, NULL, NULL, 37, 11, 24),
	(10, 1, 'W', NULL, NULL, 21, 8, 34, 47),
	(10, 2, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 3, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 4, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 5, 'G', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 6, 'GB', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 7, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 8, 'B', NULL, NULL, NULL, 54, NULL, NULL),
	(10, 9, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 10, 'BY', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 11, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 12, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 13, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 15, 'W', NULL, NULL, NULL, 38, 12, 25),
	(11, 1, 'W', NULL, NULL, 20, 7, 33, 46),
	(11, 2, 'W', NULL, NULL, 19, 6, 32, 45),
	(11, 3, 'W', NULL, NULL, 18, 5, 31, 44),
	(11, 4, 'W', NULL, NULL, 17, 4, 30, 43),
	(11, 5, 'GB', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 6, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 7, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 8, 'B', NULL, NULL, NULL, 53, NULL, NULL),
	(11, 9, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 10, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 11, 'BY', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 12, 'W', NULL, NULL, 3, 42, 16, 29),
	(11, 13, 'W', NULL, NULL, 2, 41, 15, 28),
	(11, 14, 'Y', NULL, NULL, 1, 40, 14, 27),
	(11, 15, 'W', NULL, NULL, NULL, 39, 13, 26),
	(12, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 2, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 3, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 5, 'W', NULL, NULL, 16, 3, 29, 42),
	(12, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 8, 'B', NULL, NULL, NULL, 52, NULL, NULL),
	(12, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 11, 'W', NULL, NULL, 4, 43, 17, 30),
	(12, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 13, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 2, 'W', 'B', 'B3', NULL, NULL, NULL, NULL),
	(13, 3, 'W', 'B', 'B1', NULL, NULL, NULL, NULL),
	(13, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 5, 'W', NULL, NULL, 15, 2, 28, 41),
	(13, 6, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 7, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 8, 'B', NULL, NULL, NULL, 51, NULL, NULL),
	(13, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 11, 'W', NULL, NULL, 5, 44, 18, 31),
	(13, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 13, 'W', 'Y', 'Y3', NULL, NULL, NULL, NULL),
	(13, 14, 'W', 'Y', 'Y1', NULL, NULL, NULL, NULL),
	(13, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 2, 'W', 'B', 'B4', NULL, NULL, NULL, NULL),
	(14, 3, 'W', 'B', 'B2', NULL, NULL, NULL, NULL),
	(14, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 5, 'B', NULL, NULL, 14, 1, 27, 40),
	(14, 6, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 7, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 8, 'B', NULL, NULL, NULL, 50, NULL, NULL),
	(14, 9, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 10, 'W', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 11, 'W', NULL, NULL, 6, 45, 19, 32),
	(14, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 13, 'W', 'Y', 'Y4', NULL, NULL, NULL, NULL),
	(14, 14, 'W', 'Y', 'Y2', NULL, NULL, NULL, NULL),
	(14, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 1, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 2, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 3, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 4, 'B', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 5, 'W', NULL, NULL, 13, NULL, 26, 39),
	(15, 6, 'W', NULL, NULL, 12, NULL, 25, 38),
	(15, 7, 'W', NULL, NULL, 11, NULL, 24, 37),
	(15, 8, 'W', NULL, NULL, 10, 49, 23, 36),
	(15, 9, 'W', NULL, NULL, 9, 48, 22, 35),
	(15, 10, 'W', NULL, NULL, 8, 47, 21, 34),
	(15, 11, 'W', NULL, NULL, 7, 46, 20, 33),
	(15, 12, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 13, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 14, 'Y', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 15, 'Y', NULL, NULL, NULL, NULL, NULL, NULL);

-- Dumping structure for procedure adise23_griniaris.clean_board
DELIMITER //
CREATE PROCEDURE `clean_board`()
BEGIN
	REPLACE INTO  board SELECT * FROM  board_empty;
END//
DELIMITER ;

-- Dumping structure for πίνακας adise23_griniaris.game_status
CREATE TABLE IF NOT EXISTS `game_status` (
  `status` enum('not active','initialized','started','ended','aborded') NOT NULL DEFAULT 'not active',
  `p_turn` enum('R','G','B','Y') DEFAULT NULL,
  `result` enum('B','R','G','Y') DEFAULT NULL,
  `last_change` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table adise23_griniaris.game_status: ~0 rows (approximately)

-- Dumping structure for procedure adise23_griniaris.move_piece
DELIMITER //
CREATE PROCEDURE `move_piece`(x1 TINYINT,y1 TINYINT,x2 TINYINT,y2 TINYINT)
BEGIN
DECLARE p, p_color CHAR;
SELECT piece, piece_color INTO p, p_color
FROM `board` WHERE X=x1 AND Y=y1;
UPDATE board
SET piece=p, piece_color=p_color
WHERE X=x2 AND Y=y2;
UPDATE board
SET piece=NULL,piece_color=NULL
WHERE X=x1 AND Y=y1;
END//
DELIMITER ;

-- Dumping structure for πίνακας adise23_griniaris.players
CREATE TABLE IF NOT EXISTS `players` (
  `username` varchar(20) DEFAULT NULL,
  `piece_color` enum('B','R','G','Y') NOT NULL,
  `token` varchar(100) DEFAULT NULL,
  `last_action` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`piece_color`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table adise23_griniaris.players: ~4 rows (approximately)
INSERT INTO `players` (`username`, `piece_color`, `token`, `last_action`) VALUES
	(NULL, 'B', NULL, '2023-11-20 11:05:50'),
	(NULL, 'R', NULL, '2023-11-20 11:07:30'),
	(NULL, 'G', NULL, '2023-11-20 11:08:05'),
	(NULL, 'Y', NULL, '2023-11-20 11:11:40');

-- Dumping structure for trigger adise23_griniaris.game_status_update
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER game_status_update BEFORE UPDATE
ON game_status
FOR EACH ROW BEGIN
SET NEW.last_change = NOW();
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
